app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import Index, detail, ContactView

urlpatterns = [
    path('', views.Index.as_view()),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('list/', views.BlogListView.as_view(), name='list'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

class UserManager(BaseUserManager):

    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    email = models.EmailField(
        max_length=255,
        unique=True,
    )

    is_active = models.BooleanField(default=True)

    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True
    
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

app/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=50, default='')
    text = models.TextField(max_length=500, default='')
    author = models.CharField(max_length=30, default='')
    created_at = models.DateField(auto_now_add=True)
    updated_st = models.DateField(auto_now=True)
    images = models.ImageField(blank=True, upload_to='images/')
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField(max_length=500, default='')
    name = models.CharField(max_length=20, default='')
    created_at = models.DateField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:10]


class Contact(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(max_length=50)
    text = models.TextField(max_length=500, default='')

    def __str__(self):
        return self.name

app/forms.py
from django import forms
from .models import Comment
from django.core.mail import EmailMessage

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {
            'text',
            'name',
        }


class ContactForm(forms.Form):
    name = forms.CharField(label='')
    email = forms.EmailField(label='')
    text = forms.CharField(label='', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        text = self.cleaned_data['text']

        messages = EmailMessage(subject=name + 'からの問い合わせ',
                                body=text,
                                from_email=email,
                                to=["kinnkann1991@gmail.com"],
                                cc=[email])

        messages.send()

accounts/views.py
from django.shortcuts import render

# Create your views here.

app/views.py
from app.models import Blog
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, FormView
from .models import Blog, Comment
from .forms import CommentForm, ContactForm
from django.urls import reverse_lazy

# Create your views here.

class Index(ListView):
    model = Blog
    template_name = 'app/index.html'
    paginate_by = 3


def detail(request, pk):
    obj = Blog.objects.get(pk=pk)
    comments = Comment.objects.filter(blog=obj)
    context = {
        'blog': obj,
        'comments': comments,
    }
    if request.method =='POST':
        if request.POST.get('like_count', None):
            obj.count += 1
            obj.save()
        # like_countのnameが入ったものにpostが実行されたときに
        # countが１増加するようになる

        form = CommentForm(request.POST)
        if form.is_valid():
            text = form.save(commit=False)
            text.blog = obj
            text.save()

        # POSTを受け取った場合,formsのCommentFormを呼び出す
        # htmlのnameとformsの変数があっているのを確認する
        # validationを行って問題なければdbに保存する

    # Blogの個別ページをobjに代入
    # それをcontext内にkey=blog, value:model変数になっている
    # ロードするときは{{blog.title}}で出力可能

    return render(request, 'app/detail.html', context)

    # コメント反映のコピー
    # obj = Blog.objects.get(pk=pk)
    # comments = Comment.objects.filter(blog=obj)
    # context = {
    #     'blog': obj,
    #     'comments': comments,
    # }
    # if request.method =='POST':
    #     form = CommentForm(request.POST)
    #     if form.is_valid():
    #         text = form.save(commit=False)
    #         text.blog = obj
    #         text.save()


class BlogListView(ListView):
    model = Blog
    template_name = 'app/blog_list.html'


class ContactView(FormView):
    template_name = 'app/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy("contact")

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

app/templates/app/blog_list.html
{% extends 'base.html' %}

{% block contents %}

{% for blog in object_list %}
<div class="media mb-4">
    <svg class="bd-placeholder-img mr-3" width="64" height="64" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 64x64"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em">64x64</text></svg>
    <div class="media-body">
        <a href="{% url 'detail' blog.pk %}">
        <h5 class="mt-0 border-bottom">{{ blog.title }} {{ blog.created_at }}</h5>
        {{ blog.text }}
        </a>
    </div>
</div>
{% endfor %}


{% endblock %}

app/templates/app/contact.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block contents %}
<form method="post">
    {% csrf_token %}
    <!-- {{ form.non_field_errors }} -->

    
    <div>
        <p>名前：{{ form.name|add_class:'form-control' }}</p>
        <p>メールアドレス：{{ form.email|add_class:'form-control' }}</p>
        <p>お問い合わせ内容：{{ form.text|add_class:'form-control' }}</p>
    </div>
    
    

    <!-- {{ field.errors }} -->
    
    <button type='submit' class="btn btn-outline-dark">送信</button>
</form>



{% endblock %}

app/templates/app/detail.html
{% extends 'base.html' %}

{% block contents %}

{% include 'snippets/blog_detail.html' %}

{% include 'snippets/comment_list.html' %}

{% include 'snippets/comment_create.html' %}


{% endblock %}

app/templates/app/index.html
{% extends 'base.html' %}

{% block contents %}

{% include 'snippets/index_list.html' %}

{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="ja">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>ブログ</title>
</head>

<body>
    <!-- navbar template -->
    {% include 'snippets/head_navbar.html' %}
    <!-- end navbar -->
    <div class="text-center my-5">
        <h1 class="font-italic">welcome home page</h1>
        <p>Djangoで勉強してきたこととかを書いていきます</p>
    </div>
    

    <!-- main contents -->
    <div class="container">
        <div class="row">
            <div class="col-sm-9">
                {% block contents %}
                
                {% endblock %}
            </div> 
    
            <div class="col-sm-3">
                <div class="sticky-top vh-100 side">
                    <img class='img-fluid rounded-circle' src="images/20210912003750.jpg" alt="">
                    <p>あああああああああああああああああああああああ</p>
                </div>
            </div>
        
        </div>    
    </div>
    <!-- end main contents -->

    <footer>
        <div class="fixed-bottom bg-light">
            <p class="text-center">copyright ©︎ 2021</p>
        </div>
        
         
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

<!-- {% for object in object_list %}

    <a href="detail/{{ object.pk }}/">{{ object.title }}</a>

    {% endfor %} -->

app/templates/snippets/blog_detail.html
<img src="{{ blog.images.url }}" alt="">
<p>{{ blog.title }} {{ blog.created_at }}</p>
<p>{{ blog.text|linebreaksbr }}</p>
<p>{{ blog.author }}</p>

app/templates/snippets/comment_create.html
<form method="POST">
    {% csrf_token %}
    <label for="" class="form-label">コメント欄</label>
    <textarea class="form-control" name="text" id="" cols="" rows="5"></textarea>
    <input name="name" class="form-control mt-3 mb-3" cols="6" placeholder="名前">
    <button type='submit' class="btn btn-outline-dark">コメントする</button>
    <div class="mb-5"></div>
</form>
<!-- nameの部分をmodels Commentにあわせないと保存できないので注意 -->
<!-- formsから出力でなくhtmlから情報を受け取って保存するのでPOSTで処理を行うよ -->
<!-- viewsの方でPOSTがきたらどうするか記述する -->
    

app/templates/snippets/comment_list.html
{% for comment in comments %}
<div class="media mb-4">
    <svg class="bd-placeholder-img mr-3" width="64" height="64" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 64x64"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em">64x64</text></svg>
    <div class="media-body">
        <h5 class="mt-0 border-bottom">{{ comment.name }} {{ comment.created_at }}</h5>
        {{ comment.text }}
    </div>
</div>
{% endfor %}

<!-- {% for comment in comments %}
    <p>{{ comment.text }}</p>
    <p>{{ comment.name }}</p>
    <p>{{ comment.created_at }}</p>
    <div>----------------------------------</div>
    {% endfor %}
     ループ分じゃないとなぜか値がとれない 
</div> -->

app/templates/snippets/head_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-white">
    <!-- <a class="navbar-brand" href="#">Navbar</a> -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNav">
        <ul class="navbar-nav mx-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-ite">
                <a class="nav-link" href="{% url 'list' %}">all blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">contact</a>
            </li>
        </ul>
    </div>
</nav>

app/templates/snippets/index_list.html
<div class="card-deck">
    {% for object in object_list %}
    <div class="card">
        <a href="detail/{{ object.pk }}/">
            <img class='card-img-top' src='{{ object.images }}' alt=''>
            <div class="card-body">
                {{ object.title }}
            </div>
            <div class="card-footer">
                bbbbb
            </div>
        </a>
    </div>
    {% endfor %}
</div>